### ISSUE TITLE
Colob内で複数動かないところがある

### ISSUE THREAD

**Issue by RyoKurosaki** [AlpacaDB/jquants-api-sample#38]
stock_fin(財務情報)のソートのキーにDisclosedUnixTimeを使用しているが、アップデートされた為か実際のJ-Quantas APIの変数はDisclosedTimeになっている。

stock_list(銘柄一覧)の
`stock_list_load.loc[(stock_list_load["Code"].str.len() == 5) & (stock_list_load["Code"].str[-1] == "0"), "Code"] = stock_list_load.loc[(stock_list_load["Code"].str.len() == 5) & (stock_list_load["Code"].str[-1] == "0"), "Code"].str[:-1]`
部分で

> AttributeError: Can only use .str accessor with string values!

が出る。

機械学習の初学ですが、どうせなら興味のある株式マーケットに関連することをしたいと思い非常に参考になっておりますので、是非アップデートお願いします。

**Comment by hiohiohio** [comment]
@RyoKurosaki ご報告いただきありがとうございます。
- DisclosedTime については以下のPR [1] の内容で対応できるかとおもいます。
- 銘柄コード (Code) が文字列型として読み込まれていないことでエラーが発生しているように見えます。こちらは調査して必要であれば以下のPRに修正対応を実施します。

*1 https://github.com/AlpacaDB/jquants-api-sample/pull/37/files

**Comment by hiohiohio** [comment]
@RyoKurosaki 
ご報告いただいたstock_list(銘柄一覧)でエラーとなる件、上記のPRの内容を手元の環境で実施してエラーが出ないことを確認したためマージしました。

**Comment by RyoKurosaki** [comment]
@hiohiohio ありがとうございます！
最初に対象ファイルをお伝え出来ておらず申し訳ありません。
20220928_jquantsapi_tutorial.ipynb
は対応予定でしょうか？
よろしくお願いします。

**Comment by hiohiohio** [comment]
最低限上から通して実行できるように修正してみますね。

**Comment by hiohiohio** [comment]
@RyoKurosaki 先ほど修正をマージいたしました。手元の Colab で実行を確認していますが、メモリ不足など実行に問題がありましたらご連絡いただけますとありがたいです。

**Comment by RyoKurosaki** [comment]
@hiohiohio 
ありがとうございます！超絶感謝です！ご確認させて頂きます。
